import { Metadata } from "next";
import { ListUsers } from "./ListUsers";

export const metadata: Metadata = {
  title: "Hospital | dashboard",
  description: "Generated by create SmadCode",
};

export default function Dashboard() {
  return (
    <main className="w-full h-full">
      <ListUsers />
    </main>
  )
}