import { Metadata } from "next";
import { NewDoctorForm } from "./NewDoctorForm";

export const metadata: Metadata = {
  title: "Hospital | Doctor",
  description: "Generated by create SmadCode",
};

export default function NewDoctor() {
  return (
    <main className="w-full h-auto">
      <NewDoctorForm />
    </main>
  )
}
