import { ReactNode } from "react";
import { Header } from "@/app/components/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hospital | Home",
  description: "Generated by create SmadCode",
};

interface PagesLayoutProps {
  children: ReactNode;
}

export default function PagesLayout({ children }: PagesLayoutProps) {
  return (
    <main className='w-screen h-screen'>
      <Header />
      {children}
    </main>
  );
}
