import { ReactNode } from "react";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import { MantineProvider } from '@mantine/core';
import { QueryClientProvider } from "@/app/Providers/QueryClientProvider";
import { theme } from './mantineTheme';
import { Header } from "./components/Header";
import '@mantine/core/styles.css';
import "./globals.css";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "test Next",
  description: "Generated by create SmadCode",
  icons: {
    icon: "/favicon.png",
  },
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`antialiased h-screen bg-mygray-100  ${poppins.className}`}>
        <QueryClientProvider>
          <MantineProvider theme={theme}>
            <Header />
            {children}
          </MantineProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
